name: goat
channels:
  - conda-forge        
  - defaults
dependencies:
  - python=3.7        
  - django=1.11       
  - geckodriver=0.21
  - selenium=3
  - firefox
  - lxml
  - cssselect
  - pygments
  - requests
  - fabric3
  - pytest
  - pytest-xdist